export interface SemanticRelationDefinition {
  name: string;
  grain: string;
  description: string;
  columns: readonly string[];
}

export const SEMANTIC_RELATIONS = [
  {
    name: "v_customers",
    grain: "one row per customer / business partner",
    description: "Customer master data including blocking, grouping, archiving, and creation attributes.",
    columns: [
      "customer_id",
      "business_partner_id",
      "customer_name",
      "customer_full_name",
      "business_partner_category",
      "business_partner_grouping",
      "business_partner_is_blocked",
      "is_marked_for_archiving",
      "correspondence_language",
      "created_by_user",
      "creation_date",
      "creation_time",
      "first_name",
      "last_name",
      "form_of_address",
      "industry",
      "last_change_date",
      "organization_bp_name_1",
      "organization_bp_name_2",
    ],
  },
  {
    name: "v_products",
    grain: "one row per product",
    description: "Product master data including descriptions, units, weights, lifecycle flags, and grouping.",
    columns: [
      "product_id",
      "product_description",
      "product_type",
      "product_old_id",
      "product_group",
      "base_unit",
      "division",
      "gross_weight",
      "net_weight",
      "weight_unit",
      "created_by_user",
      "creation_date",
      "cross_plant_status",
      "cross_plant_status_validity_date",
      "industry_sector",
      "is_marked_for_deletion",
      "last_change_date",
      "last_change_date_time",
    ],
  },
  {
    name: "v_plants",
    grain: "one row per plant",
    description: "Plant master data including organizational assignments, valuation, and language/calendar settings.",
    columns: [
      "plant_id",
      "plant_name",
      "address_id",
      "default_purchasing_organization",
      "distribution_channel",
      "division",
      "factory_calendar",
      "is_marked_for_archiving",
      "language",
      "plant_category",
      "plant_customer",
      "plant_supplier",
      "sales_organization",
      "valuation_area",
    ],
  },
  {
    name: "v_sales_orders",
    grain: "one row per sales order header",
    description: "Sales order header data including customer, values, statuses, org assignments, and incoterms.",
    columns: [
      "sales_order_id",
      "customer_id",
      "customer_name",
      "sales_order_type",
      "sales_organization",
      "distribution_channel",
      "organization_division",
      "sales_group",
      "sales_office",
      "creation_date",
      "created_by_user",
      "last_change_date_time",
      "requested_delivery_date",
      "pricing_date",
      "total_net_amount",
      "transaction_currency",
      "overall_delivery_status",
      "overall_billing_status",
      "overall_sd_doc_reference_status",
      "header_billing_block_reason",
      "delivery_block_reason",
      "incoterms_classification",
      "incoterms_location_1",
      "customer_payment_terms",
      "total_credit_check_status",
    ],
  },
  {
    name: "v_sales_order_items",
    grain: "one row per sales order item",
    description: "Sales order item data with product, customer, plant, quantity, value, and item-level statuses.",
    columns: [
      "sales_order_id",
      "sales_order_item_id",
      "customer_id",
      "customer_name",
      "product_id",
      "product_description",
      "product_group",
      "production_plant_id",
      "production_plant_name",
      "storage_location",
      "requested_quantity",
      "order_quantity",
      "requested_quantity_unit",
      "net_amount",
      "transaction_currency",
      "material_group",
      "sales_order_item_category",
      "item_billing_block_reason",
      "sales_document_rejection_reason",
    ],
  },
  {
    name: "v_deliveries",
    grain: "one row per delivery header",
    description: "Outbound delivery header data including goods movement, picking, POD, and blocking statuses.",
    columns: [
      "delivery_document_id",
      "actual_goods_movement_date",
      "actual_goods_movement_time",
      "creation_date",
      "creation_time",
      "delivery_block_reason",
      "hdr_general_incompletion_status",
      "header_billing_block_reason",
      "last_change_date",
      "overall_goods_movement_status",
      "overall_picking_status",
      "overall_proof_of_delivery_status",
      "shipping_point",
    ],
  },
  {
    name: "v_delivery_items",
    grain: "one row per delivery item",
    description: "Outbound delivery item data with referenced sales order item, plant, quantity, and storage details.",
    columns: [
      "delivery_document_id",
      "delivery_document_item_id",
      "reference_sales_order_id",
      "reference_sales_order_item_id",
      "customer_id",
      "customer_name",
      "product_id",
      "product_description",
      "plant_id",
      "plant_name",
      "storage_location",
      "actual_delivery_quantity",
      "delivery_quantity_unit",
      "batch",
      "item_billing_block_reason",
      "last_change_date",
    ],
  },
  {
    name: "v_billing_documents",
    grain: "one row per billing document header",
    description: "Billing header data including invoice type, accounting document linkage, customer, and cancellation status.",
    columns: [
      "billing_document_id",
      "billing_document_type",
      "billing_document_date",
      "billing_document_is_cancelled",
      "cancelled_billing_document",
      "company_code",
      "fiscal_year",
      "accounting_document_id",
      "customer_id",
      "customer_name",
      "total_net_amount",
      "transaction_currency",
      "creation_date",
      "creation_time",
      "last_change_date_time",
    ],
  },
  {
    name: "v_billing_items",
    grain: "one row per billing document item",
    description: "Billing item data with product, customer, referenced delivery item, and derived sales order linkage.",
    columns: [
      "billing_document_id",
      "billing_document_item_id",
      "customer_id",
      "customer_name",
      "product_id",
      "product_description",
      "billing_quantity",
      "billing_quantity_unit",
      "net_amount",
      "transaction_currency",
      "reference_delivery_document_id",
      "reference_delivery_document_item_id",
      "sales_order_id",
      "sales_order_item_id",
    ],
  },
  {
    name: "v_journal_entries_ar",
    grain: "one row per AR journal entry item",
    description: "Accounts receivable journal entries with amounts, accounting classifications, and customer linkage.",
    columns: [
      "journal_entry_id",
      "company_code",
      "fiscal_year",
      "accounting_document_id",
      "accounting_document_item_id",
      "accounting_document_type",
      "reference_billing_document_id",
      "posting_date",
      "document_date",
      "customer_id",
      "customer_name",
      "amount_in_transaction_currency",
      "transaction_currency",
      "amount_in_company_code_currency",
      "company_code_currency",
      "assignment_reference",
      "clearing_accounting_document",
      "clearing_date",
      "clearing_doc_fiscal_year",
      "gl_account",
      "financial_account_type",
      "profit_center",
      "cost_center",
      "last_change_date_time",
    ],
  },
  {
    name: "v_payments_ar",
    grain: "one row per AR payment item",
    description: "Accounts receivable payment items with clearing, GL, profit center, and customer linkage.",
    columns: [
      "payment_id",
      "company_code",
      "fiscal_year",
      "accounting_document_id",
      "accounting_document_item_id",
      "customer_id",
      "customer_name",
      "amount_in_transaction_currency",
      "transaction_currency",
      "amount_in_company_code_currency",
      "company_code_currency",
      "assignment_reference",
      "clearing_accounting_document",
      "clearing_date",
      "clearing_doc_fiscal_year",
      "invoice_reference",
      "invoice_reference_fiscal_year",
      "sales_document",
      "sales_document_item",
      "posting_date",
      "document_date",
      "gl_account",
      "financial_account_type",
      "profit_center",
      "cost_center",
    ],
  },
  {
    name: "v_customer_company_assignments",
    grain: "one row per customer and company code assignment",
    description: "Customer-company assignment details including payment terms and reconciliation account.",
    columns: ["customer_id", "customer_name", "company_code", "payment_terms", "reconciliation_account"],
  },
  {
    name: "v_customer_sales_area_assignments",
    grain: "one row per customer sales area assignment",
    description: "Customer sales area configuration including sales org, distribution channel, division, and shipping condition.",
    columns: [
      "customer_id",
      "customer_name",
      "sales_area_key",
      "sales_organization",
      "distribution_channel",
      "division",
      "customer_payment_terms",
      "shipping_condition",
    ],
  },
  {
    name: "v_product_plants",
    grain: "one row per product and plant assignment",
    description: "Product to plant assignment data including purchasing group and procurement type.",
    columns: [
      "product_id",
      "product_description",
      "plant_id",
      "plant_name",
      "purchasing_group",
      "procurement_type",
    ],
  },
  {
    name: "v_product_storage_locations",
    grain: "one row per product, plant, and storage location assignment",
    description: "Product storage location data across plants.",
    columns: ["product_id", "product_description", "plant_id", "plant_name", "storage_location"],
  },
  {
    name: "v_o2c_flow_item",
    grain: "one row per sales order item flow",
    description: "Curated order-to-cash line-level flow from sales order item through delivery, billing, posting, and payment.",
    columns: [
      "sales_order_id",
      "sales_order_item_id",
      "customer_id",
      "customer_name",
      "product_id",
      "product_description",
      "production_plant_id",
      "storage_location",
      "requested_quantity",
      "order_net_amount",
      "currency",
      "delivery_count",
      "first_delivery_document_id",
      "billing_document_count",
      "first_billing_document_id",
      "accounting_document_id",
      "payment_count",
      "flow_status",
    ],
  },
  {
    name: "v_billing_trace",
    grain: "one row per billing document item trace",
    description: "Curated billing-centric flow from billing item back to sales order and forward to posting and payment.",
    columns: [
      "billing_document_id",
      "billing_document_item_id",
      "billing_document_type",
      "billing_document_date",
      "billing_document_is_cancelled",
      "company_code",
      "fiscal_year",
      "accounting_document_id",
      "sales_order_id",
      "sales_order_item_id",
      "delivery_document_id",
      "delivery_document_item_id",
      "customer_id",
      "customer_name",
      "product_id",
      "product_description",
      "billing_net_amount",
      "currency",
      "journal_entry_count",
      "payment_count",
      "payment_clearing_documents",
      "flow_status",
    ],
  },
  {
    name: "v_entity_lookup",
    grain: "one row per graph node",
    description: "Search index over graph nodes for UI and LLM entity grounding.",
    columns: ["node_id", "node_type", "entity_id", "label", "subtitle", "search_text"],
  },
  {
    name: "v_customer_growth",
    grain: "one row per customer and order date",
    description: "Customer day-level trend summary including delivered, billed, posted, and paid counts.",
    columns: [
      "customer_id",
      "customer_name",
      "order_date",
      "order_year",
      "order_month",
      "sales_order_count",
      "sales_order_item_count",
      "total_order_amount",
      "delivered_item_count",
      "billed_item_count",
      "posted_item_count",
      "paid_item_count",
    ],
  },
  {
    name: "v_customer_status",
    grain: "one row per customer",
    description: "Curated customer status summary used for blocked/active analysis.",
    columns: [
      "customer_id",
      "customer_name",
      "business_partner_is_blocked",
      "is_marked_for_archiving",
      "creation_date",
    ],
  },
  {
    name: "v_product_details",
    grain: "one row per product",
    description: "Compatibility alias for product master detail lookups.",
    columns: [
      "product_id",
      "product_description",
      "product_type",
      "product_old_id",
      "product_group",
      "base_unit",
      "division",
      "gross_weight",
      "net_weight",
      "weight_unit",
    ],
  },
] as const satisfies readonly SemanticRelationDefinition[];

export const SEMANTIC_RELATIONSHIPS = [
  "v_sales_orders.customer_id joins v_customers.customer_id",
  "v_sales_order_items.sales_order_id joins v_sales_orders.sales_order_id",
  "v_sales_order_items.product_id joins v_products.product_id",
  "v_sales_order_items.production_plant_id joins v_plants.plant_id",
  "v_delivery_items.reference_sales_order_id and reference_sales_order_item_id join v_sales_order_items.sales_order_id and sales_order_item_id",
  "v_delivery_items.delivery_document_id joins v_deliveries.delivery_document_id",
  "v_delivery_items.plant_id joins v_plants.plant_id",
  "v_billing_documents.customer_id joins v_customers.customer_id",
  "v_billing_items.billing_document_id joins v_billing_documents.billing_document_id",
  "v_billing_items.reference_delivery_document_id and reference_delivery_document_item_id join v_delivery_items.delivery_document_id and delivery_document_item_id",
  "v_billing_items.product_id joins v_products.product_id",
  "v_journal_entries_ar.reference_billing_document_id joins v_billing_documents.billing_document_id",
  "v_journal_entries_ar.customer_id joins v_customers.customer_id",
  "v_payments_ar.customer_id joins v_customers.customer_id",
  "v_payments_ar.accounting_document_id can be compared with v_billing_documents.accounting_document_id or v_journal_entries_ar.accounting_document_id when tracing AR postings and clearings",
  "v_customer_company_assignments.customer_id joins v_customers.customer_id",
  "v_customer_sales_area_assignments.customer_id joins v_customers.customer_id",
  "v_product_plants.product_id joins v_products.product_id and plant_id joins v_plants.plant_id",
  "v_product_storage_locations.product_id joins v_products.product_id and plant_id joins v_plants.plant_id",
  "v_o2c_flow_item is already a curated sales-order-item flow and often avoids complex joins",
  "v_billing_trace is already a curated billing-item flow and often avoids complex joins",
];

export const UNSUPPORTED_TOPIC_HINTS = [
  "employees, headcount, or HR data",
  "shipping costs or freight charges",
  "weather or external forecasts",
  "vendors, suppliers, or procurement lead times",
  "costs, profit, margin, or competitor pricing",
  "warehouse managers or personnel assignments",
  "returns, RMAs, or customer support tickets",
  "customer satisfaction, surveys, or feedback",
  "manufacturing equipment, assets, or BOM/raw-material details",
] as const;

export const ALLOWED_RELATION_NAMES: Set<string> = new Set(SEMANTIC_RELATIONS.map((relation) => relation.name));
export const ALLOWED_COLUMN_NAMES: Set<string> = new Set(SEMANTIC_RELATIONS.flatMap((relation) => relation.columns));

export function formatSemanticCatalogForPrompt() {
  return SEMANTIC_RELATIONS.map((relation) => {
    return `- ${relation.name}: ${relation.description} Grain: ${relation.grain}. Columns: ${relation.columns.join(", ")}`;
  }).join("\n");
}

export function formatSemanticRelationshipsForPrompt() {
  return SEMANTIC_RELATIONSHIPS.map((relationship) => `- ${relationship}`).join("\n");
}
